2023-06-14 00:16:14,342 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 940851ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 00:33:44,906 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1050562ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 00:51:42,389 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1077478ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 01:08:04,193 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 981801ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 01:26:01,882 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1077534ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 01:43:09,200 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1027313ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 02:01:14,188 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1064980ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 02:18:45,747 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1051555ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 02:36:24,313 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1058563ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 02:52:35,900 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 971528ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 04:12:51,214 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 920793ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 04:29:25,872 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 994657ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 05:02:29,224 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 931725ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 05:18:16,833 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 947606ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 06:11:11,944 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1060628ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 06:42:02,224 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 942667ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 06:58:54,793 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1012565ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 07:33:07,239 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 980803ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 07:49:57,888 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1010647ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 08:25:06,242 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1075659ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 08:42:15,915 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1029670ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 09:14:21,254 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 914817ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 09:32:53,347 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1052085ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 09:48:57,243 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 963893ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 10:06:00,817 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1023570ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 10:36:24,257 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 921786ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 11:42:15,275 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1035007ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 11:58:21,811 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 966514ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 12:30:07,027 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 913654ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 13:16:56,805 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 974526ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 13:48:37,975 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 933648ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 14:22:09,286 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 991724ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 15:12:17,286 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1069741ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 15:30:05,872 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1068584ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 16:02:12,305 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 909805ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 16:51:41,309 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 920637ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 17:08:07,918 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 986605ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 17:40:27,296 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 939689ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 17:57:01,864 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 994567ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 18:30:10,318 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 1067769ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 18:46:46,840 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 996516ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 19:20:11,007 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 995551ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 19:53:08,330 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 913781ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 20:09:23,946 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 975612ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

2023-06-14 20:38:08,508 ERROR 81226 nodejs.ClusterClientNoResponseError: client no response in 819942ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/wwei/Documents/my_github/wwei-lego-backend/node_modules/.pnpm/cluster-client@3.4.0/node_modules/cluster-client/lib/leader.js:79:25)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
name: "ClusterClientNoResponseError"
pid: 81226
hostname: wangweideMacBook-Pro.local

